### ISSUE TITLE
CSS issues on some sites

### ISSUE THREAD

**Issue by arlogilbert** [osano/privacymonitor-chrome#7]
On numerous sites the popup appears different.

The problem is that the popup is inheriting some styles from the CSS style sheet of the page.

To correct this, all CSS needs to be handled at an ID level rather than class level and each CSS rule needs to include the settings for all possible CSS entries because the master document occasionally includes something by default (e.g. line height).

**Comment by pgoforth** [comment]
As a point of fact, CSS should almost never be `#id` based. The CSS should use class prefixes and/or cascading specificity. If we have having CSS conflicts with class names, we can fix that easily enough.
